#!/usr/bin/env bash
#A while loop to print Best school 10 times and Hi after the 9th iteration

count=0
while [ $count -lt 10 ]
do
    if [ $count == 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((count++))
done