#!/usr/bin/env bash
#A while loop to print Best school 10 times and Hi after the 9th iteration

count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((count++))
done